### ISSUE TITLE
Add a toggle button for clutchless downshift

### ISSUE THREAD

**Issue by caljay98** [gopher-motorsports/transmission_control_module23#7]
This could potentially save some time and a lot of air on downshifts. We will have to test it a lot to see if the drivers like it though

**Comment by AlexT2052** [comment]
Should this allow the driver to still be able to interject and pull the clutch if they want during the shift or say no clutch at all, and in the backups states for this (like when it fails to downshift correctly), should it pull the clutch then?

**Comment by caljay98** [comment]
Yes the driver should still be able to interject and do a clutched shift. I would also say failed shifts should still pull the clutch to complete the shift.
